server:
  port: 8080

spring:
  profiles:
    active: "h2"
  main:
    banner-mode: "off"
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connectionTimeout: 30000
      idle-timeout: 300000
      maxLifetime: 1200000
      minimum-idle: 2
      maximum-pool-size: 5

---

spring:
  profiles: h2
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:ServiceDB;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: Nikita
    password:
    platform: h2
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.HSQLDialect